# Generated by Django 3.2.6 on 2022-03-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_updateorder_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bsn_location',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='bsn_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
